language: php
php:
  - 7.1
  - 7.2
before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - mysql -e "CREATE DATABASE ${DB_DATABASE};"
  - php artisan key:generate
script:
  - php artisan migrate --no-interaction
  - vendor/bin/phpunit tests
