language: php
php:
  - 7.1
  - 7.2
before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - mysql -e "CREATE DATABASE ${DB_NAME};"
  - php artisan key:generate
script:
  - php artisan migrate --no-interaction
  - vendor/bin/phpunit tests
env:
  matrix:
    secure: 2Ef7S8IxwYGn+064hgC/FbDYoUh6bozX2+U+Xdb6pGeZK/W3GUjhzY/kYPB5r3tWf4gVZa+UZIgYIN8wosKDohL+5uEn8ab2nztq8OMzW/FaBY21dbR4/7oMq4KXHCE68zhPttHYhwD6xrGinenzuEwNtJ1+ekE2uA9nNvw/lDRQqQvN67ZOPFKYtiD56707P7dHEfylFHAaYwnirvZrxM+2GQAppjja1mQX6rS/vX2mNHuh3AWv+QMgdGNwRy66RNmZzEji0Lnurcf7ezQ1FmmlxeNaWFfBOGRazPGb7h5MN02YNgUrl4Xdo0RjxAJ8aj1JXNO2ifaPlCawNNevD7icilghJI9eu9xzy3utNSlTrkPFNNTrZW/J2BJR332wYRKOXwvHKdlzym0xl5Qqi+mWvvISZdtM64dlGz+bD1V6xngG4uELDC9EZnQ1yUR0OkTAQDOunleV+FvDmuNKdRfcs9gb0yJFDI3AX28sqw+LD2xo6eXZAoeVjaBykdlpVQ4sAsu22ftJAsKlJRRi9l0lnh7j3j26NrRpVVXlyLmFyfkQMGTQb4/s9D7bq3nz4XuvbDJyaALYlqGP1pxYxr8Wv9OtAYdSywshVqiJjv+XETwGmEZPbncgmLsEyJ2kmynaQPULjiUu5HSUudd8uRpFCYVl4qfEX5lAHkEGxyU=
