language: php

php:
  - 7.1
  - 7.2
  - hhvm

before_script:
  - mysql -e "CREATE DATABASE car_booking;"
  - composer install --prefer-source --no-interaction

script: 
  - vendor/bin/phpunit tests
  - php artisan migrate --no-interaction