language: php

php:
  - 7.1
  - 7.2
  - hhvm

before_script:
  - composer install --prefer-source --no-interaction
  - mysql -e "CREATE DATABASE car_booking;"
  - php artisan key:generate

script: 
  - php artisan migrate --no-interaction
  - vendor/bin/phpunit tests